services:
  app:
    build:
      context: C:/laragon/www/medical-appointment-system
    ports:
      - "8082:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: medical-appointment
      DB_USERNAME: root
      DB_PASSWORD:
      CORS_ALLOWED_ORIGINS: "http://localhost:8084,http://localhost:8086"
    volumes:
      - C:/laragon/www/medical-appointment-system:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  appointments-app:
    build:
      context: C:/laragon/www/medical-appointment-system
    ports:
      - "8084:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: medical-appointment
      DB_USERNAME: root
      DB_PASSWORD:
      CORS_ALLOWED_ORIGINS: "http://localhost:8082,http://localhost:8086"
    volumes:
      - C:/laragon/www/medical-appointment-system/app/Services/appointmentService:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  chatbot-service:
    build:
      context: C:/laragon/www/medical-appointment-system
    ports:
      - "8086:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: medical-appointment
      DB_USERNAME: root
      DB_PASSWORD:
      CORS_ALLOWED_ORIGINS: "http://localhost:8082,http://localhost:8084"
    volumes:
      - C:/laragon/www/medical-appointment-system/app/Services/chatbot-service:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: medical-appointment
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge