services:
  app:
    build:
      context: ../..
      dockerfile: kubernetes/dockerfiles/app.Dockerfile
    environment:
      - APP_ENV=testing
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=medical_test
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: medical_test
    ports:
      - "3306:3306"