name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Build y push de medical-app
      - name: Build Medical App
        run: |
          docker build -t your-dockerhub/medical-app:${{ github.sha }} ./medical-app
          docker push your-dockerhub/medical-app:${{ github.sha }}

      # Similar para appointments y chatbot
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Update Kubernetes resources
        run: |
          kubectl set image deployment/medical-app medical-app=your-dockerhub/medical-app:${{ github.sha }}