name: Deploy Medical System

on:
  workflow_run:
    workflows: ["Medical System CI/CD"]
    types:
      - completed
    branches: [main, develop]

env:
  K8S_NAMESPACE: default

jobs:
  deploy:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          
      - name: Deploy to Kubernetes
        run: |
          # Update deployments
          cd ci/scripts
          ./deploy.sh
        shell: powershell
        
      - name: Verify Deployment
        run: |
          kubectl get pods -n ${{ env.K8S_NAMESPACE }}
          kubectl get services -n ${{ env.K8S_NAMESPACE }}