name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Make scripts executable
        run: |
          chmod +x ci/scripts/build.sh
          chmod +x ci/scripts/test.sh
      
      - name: Run tests
        run: ./ci/scripts/test.sh
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build images using script
        run: ./ci/scripts/build.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          GITHUB_SHA: ${{ github.sha }}
          
      - name: Verify builds
        run: docker images