name: Docker Image CI

on:
  push:
    branches: [ "main", "pipeline" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - service: app
            port: 8082
          - service: appointments-app
            port: 8084
          - service: chatbot-service
            port: 8086

    steps:
      - uses: actions/checkout@v4

      # Primero hacemos login en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Configuramos Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build y test en un solo paso
      - name: Build and test ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Test separado
      - name: Test container
        run: |
          docker images
          docker run -d \
            --name ${{ matrix.service }} \
            -p ${{ matrix.port }}:80 \
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest
