name: Docker Image CI

on:
  push:
    branches: [ "pipeline" ]
  pull_request:
    branches: [ "pipeline" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run build script
        run: |
          chmod +x ./ci/scripts/build.sh
          ./ci/scripts/build.sh
        
      - name: Run tests
        run: |
          chmod +x ./ci/scripts/test.sh
          ./ci/scripts/test.sh

      - name: Deploy if successful
        if: success()
        run: |
          chmod +x ./ci/scripts/deploy.sh
          ./ci/scripts/deploy.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
