name: Docker Image CI

on:
  push:
    branches: [ "pipeline" ]
  pull_request:
    branches: [ "pipeline" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [medical-app, appointments-app, chatbot-service]
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: |
          docker build \
            --file kubernetes/dockerfiles/${{ matrix.service }}.Dockerfile \
            --tag ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest \
            --tag ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${{ github.sha }} \
            .
            
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${{ github.sha }}
