name: Docker Image CI

on:
  push:
    branches: [ "main", "pipeline" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - service: app
            port: 8082
          - service: appointments-app
            port: 8084
          - service: chatbot-service
            port: 8086

    steps:
      - uses: actions/checkout@v4

      # Usar tus credenciales de Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build ${{ matrix.service }}
        run: |
          docker build . --file Dockerfile \
            --tag ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest \
            --build-arg SERVICE=${{ matrix.service }}

      - name: Test build
        run: |
          docker run -d \
            --name test-${{ matrix.service }} \
            -p ${{ matrix.port }}:80 \
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest

      # Opcional: Push a Docker Hub
      - name: Push image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest
