name: Docker Image CI

on:
  push:
    branches: [ "main", "pipeline" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Construir y publicar imágenes
      - name: Build and push all images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/medical-app:latest
            ghcr.io/${{ github.repository_owner }}/medical-appointments:latest
            ghcr.io/${{ github.repository_owner }}/medical-chatbot:latest

      # Limpiar todo antes de probar
      - name: Clean environment
        run: |
          docker ps -aq | xargs -r docker rm -f
          docker system prune -af
          sudo killall -9 node || true
          sudo killall -9 apache2 || true
          sudo lsof -t -i:9901 | xargs -r sudo kill -9
          sudo lsof -t -i:9902 | xargs -r sudo kill -9
          sudo lsof -t -i:9903 | xargs -r sudo kill -9

      # Probar los contenedores con puertos diferentes
      - name: Test containers
        run: |
          # Probar app principal
          docker run -d --name app -p 9901:80 ghcr.io/${{ github.repository_owner }}/medical-app:latest
          sleep 10
          curl -f http://localhost:9901 || exit 1
          
          # Probar servicio de citas
          docker run -d --name appointments -p 9902:80 ghcr.io/${{ github.repository_owner }}/medical-appointments:latest
          sleep 10
          curl -f http://localhost:9902 || exit 1
          
          # Probar chatbot
          docker run -d --name chatbot -p 9903:80 ghcr.io/${{ github.repository_owner }}/medical-chatbot:latest
          sleep 10
          curl -f http://localhost:9903 || exit 1
