name: Docker Image CI

on:
  push:
    branches: [ "main", "pipeline" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push app
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/app:latest
          
      - name: Build and push appointments
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/appointments:latest

      - name: Build and push chatbot
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/chatbot:latest

      - name: Test containers
        run: |
          docker pull ghcr.io/${{ github.repository }}/app:latest
          docker pull ghcr.io/${{ github.repository }}/appointments:latest
          docker pull ghcr.io/${{ github.repository }}/chatbot:latest
          
          docker run -d --name app -p 8082:80 ghcr.io/${{ github.repository }}/app:latest
          docker run -d --name appointments -p 8084:80 ghcr.io/${{ github.repository }}/appointments:latest
          docker run -d --name chatbot -p 8086:80 ghcr.io/${{ github.repository }}/chatbot:latest

          # Esperar a que los contenedores estén listos
          sleep 30

          # Test de salud básico
          curl -f http://localhost:8082 || exit 1
          curl -f http://localhost:8084 || exit 1
          curl -f http://localhost:8086 || exit 1
